- .gitignore
> refactor: add bin to gitignore

- web/package-lock.json
- web/package.json
- web/src/routes/admin/pipelines/index.svelte
- web/src/routes/admin/repositories/index.svelte
> feat: use ag-grid to create feature rich tables

- web/src/lib/Components/Table.svelte
- web/src/lib/utility.ts
- web/src/routes/admin/pipelines/index.svelte
- web/src/routes/admin/repositories/index.svelte
> refactor: create a table component

- web/.eslintrc.cjs
- web/.prettierignore
- web/.prettierrc
- web/README.md
- web/postcss.config.cjs
- web/src/axios-instance.ts
- web/src/lib/form.ts
- web/src/lib/types.d.ts
- web/src/routes/admin/pipelines/_api.ts
- web/src/routes/admin/pipelines/index.json.ts
- web/src/stories/Button.stories.svelte
- web/src/stories/Button.svelte
- web/src/stories/Header.stories.svelte
- web/src/stories/Header.svelte
- web/src/stories/Introduction.stories.mdx
- web/src/stories/Page.stories.svelte
- web/src/stories/Page.svelte
- web/tsconfig.json
> refactor: lint frontend codebase

- web/src/lib/cellRenderer.test.ts
- web/src/lib/cellRenderer.ts
- web/src/routes/admin/pipelines/index.svelte
- web/src/routes/admin/repositories/index.svelte
> feat: open repo url in repo table

- web/src/lib/Templates/Admin/SideBar.svelte
> fix: ad pipelines and repo to sidebar

- cmd/app/main.go
- web/src/lib/Components/Pipelines/StreamingLog.svelte
> fix: use array instead of appending new lines of text to log

- cmd/app/main.go
> fix: remove read and write timeout from server

- README.md
- web/.gitignore
- web/e2e/home.spec.ts
- web/package-lock.json
- web/package.json
- web/playwright.config.ts
- web/src/routes/admin/index.svelte
Signed-off-by: Aabhas Sao <aabhassao0@gmail.com>
Basic setup for Playwright with one sample test.
Solves issue #16
> chore: setup playwright, add basic sample test

- internal/server/server.go
> fix: add address to server struct

- web/src/lib/cellRenderer.ts
- web/src/routes/admin/pipelines/[org]/[repo]/[branch]/[build].svelte
- web/src/routes/admin/pipelines/index.svelte
- This create another column in pipelines table for ACTIONS.
- Removes start btn from the PipelineDetailPage.
> feat: btn in table to stop pipelines

- web/package-lock.json
- web/package.json
- web/src/lib/Components/Flowchart.svelte
- web/src/routes/admin/pipelines/[org]/[repo]/[branch]/[build].svelte
- Installed d3-hierarchy and d3-shape to create a tree graph
- Created a flowchart component for the DAG code.
> feat: implementing DAG using d3

- web/package-lock.json
- web/package.json
> refactor: upgrade sveltekit to 1.0.0-next.305

- web/package-lock.json
- web/package.json
> refactor: upgrade sveltekit to 1.0.0-next.335

- web/vite.config.js
> fix: change default port back to 3000

- .golangci.yml
- .lighthouse/jenkins-x/pullrequest.yaml
- .lighthouse/jenkins-x/release.yaml
- .lighthouse/jenkins-x/triggers.yaml
- Makefile
- OWNERS
- OWNERS_ALIASES
- charts/jx-ui/Chart.yaml
- charts/jx-ui/Makefile
- charts/jx-ui/templates/_helpers.tpl
- charts/jx-ui/templates/deployment.yaml
- charts/jx-ui/templates/ingress.yaml
- charts/jx-ui/templates/istio.yaml
- charts/jx-ui/templates/rbac.yaml
- charts/jx-ui/templates/service.yaml
- charts/jx-ui/values.yaml
> chore: Jenkins X build pack

- .lighthouse/jenkins-x/release.yaml
> fix: add frontend build step to release pipeline

- .lighthouse/jenkins-x/pullrequest.yaml
- .lighthouse/jenkins-x/release.yaml
- hack/changelog-header.md
> refactor: set CI=true for frontend build steps

- internal/server/healthz.go
- internal/server/routes.go
Adding a new route for /healthz.
> fix: new route /healthz

- internal/server/pipelines.go
- web/src/lib/cellRenderer.ts
- web/src/routes/admin/pipelines/+page.svelte
- Adds `Name` in the `pipelines` struct
- Adds a confirmation modal for stop pipeline button in pipelines table
> feat: add modal to pipeline table

- web/package-lock.json
- web/package.json
> fix: override autoprefixer to remove color adjust warning

- web/package-lock.json
- web/package.json
> refactor: upgrade sveltekit to 1.0.0-next.497

- internal/server/server.go
> fix: dont bind to localhost

- charts/jx-ui/templates/deployment.yaml
> fix: change container port to 9200 for health check and remove args

- .lighthouse/jenkins-x/pullrequest.yaml
- charts/jx-ui/templates/deployment.yaml
> ci: add a step to build and lint helm charts
